-- Orbi App - Esquema mínimo para tiendas y entregas

CREATE TABLE IF NOT EXISTS delivery_store (
    delivery_store_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    category varchar(60) NOT NULL,
    address varchar(180) NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS delivery_product (
    delivery_product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_store_id integer NOT NULL REFERENCES delivery_store(delivery_store_id),
    name varchar(100) NOT NULL,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    is_available boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS delivery_order (
    delivery_order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_store_id integer NOT NULL REFERENCES delivery_store(delivery_store_id),
    customer_email varchar(256) NOT NULL,
    delivery_person_email varchar(256),
    delivery_address varchar(180) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Pendiente'
        CHECK (status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')),
    total numeric(10,2) NOT NULL CHECK (total >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS delivery_order_item (
    delivery_order_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_order_id integer NOT NULL REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
    delivery_product_id integer NOT NULL REFERENCES delivery_product(delivery_product_id),
    product_name varchar(100) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0)
);

CREATE INDEX IF NOT EXISTS ix_delivery_order_customer ON delivery_order(customer_email);
CREATE INDEX IF NOT EXISTS ix_delivery_order_driver ON delivery_order(delivery_person_email);
