-- Orbi App - Esquema mínimo para tiendas y entregas

CREATE TABLE IF NOT EXISTS delivery_store (
    delivery_store_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    category varchar(60) NOT NULL,
    address varchar(180) NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS delivery_product (
    delivery_product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_store_id integer NOT NULL REFERENCES delivery_store(delivery_store_id),
    name varchar(100) NOT NULL,
    price numeric(10,2) NOT NULL CHECK (price >= 0),
    is_available boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS delivery_order (
    delivery_order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_store_id integer NOT NULL REFERENCES delivery_store(delivery_store_id),
    customer_email varchar(256) NOT NULL,
    delivery_person_email varchar(256),
    delivery_address varchar(180) NOT NULL,
    status varchar(30) NOT NULL DEFAULT 'Pendiente'
        CHECK (status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')),
    total numeric(10,2) NOT NULL CHECK (total >= 0),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS delivery_order_item (
    delivery_order_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_order_id integer NOT NULL REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
    delivery_product_id integer NOT NULL REFERENCES delivery_product(delivery_product_id),
    product_name varchar(100) NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
    subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0)
);

CREATE TABLE IF NOT EXISTS ecuador_province (
    province_code varchar(2) PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ecuador_city (
    city_code varchar(4) PRIMARY KEY,
    province_code varchar(2) NOT NULL REFERENCES ecuador_province(province_code),
    name varchar(100) NOT NULL,
    UNIQUE (province_code, name)
);

CREATE TABLE IF NOT EXISTS user_profile (
    identity_user_id text PRIMARY KEY REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
    first_name varchar(80) NOT NULL,
    last_name varchar(80) NOT NULL,
    cedula varchar(10) NOT NULL UNIQUE CHECK (cedula ~ '^[0-9]{10}$'),
    address_line_1 varchar(160) NOT NULL,
    address_line_2 varchar(160) NOT NULL,
    province_code varchar(2) NOT NULL REFERENCES ecuador_province(province_code),
    city_code varchar(4) NOT NULL REFERENCES ecuador_city(city_code),
    reference varchar(240),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_delivery_order_customer ON delivery_order(customer_email);
CREATE INDEX IF NOT EXISTS ix_delivery_order_driver ON delivery_order(delivery_person_email);
CREATE INDEX IF NOT EXISTS ix_ecuador_city_province ON ecuador_city(province_code);
CREATE INDEX IF NOT EXISTS ix_user_profile_location ON user_profile(province_code, city_code);

-- Operación de inventario, entregas, auditoría y servicios internos

CREATE TABLE IF NOT EXISTS inventory_movement (
    inventory_movement_id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_product_id integer NOT NULL,
    delivery_order_id integer,
    performed_by_user_id text,
    movement_type varchar(20) NOT NULL,
    quantity_delta integer NOT NULL,
    unit_cost numeric(12,2),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_inventory_movement" PRIMARY KEY (inventory_movement_id),
    CONSTRAINT ck_inventory_movement_quantity_delta CHECK (quantity_delta <> 0),
    CONSTRAINT ck_inventory_movement_type CHECK (movement_type IN ('Entrada', 'Salida', 'Ajuste', 'Reserva', 'Liberación')),
    CONSTRAINT ck_inventory_movement_unit_cost CHECK (unit_cost IS NULL OR unit_cost >= 0),
    CONSTRAINT "FK_inventory_movement_delivery_product_delivery_product_id"
        FOREIGN KEY (delivery_product_id) REFERENCES delivery_product(delivery_product_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_inventory_movement_delivery_order_delivery_order_id"
        FOREIGN KEY (delivery_order_id) REFERENCES delivery_order(delivery_order_id) ON DELETE SET NULL,
    CONSTRAINT "FK_inventory_movement_AspNetUsers_performed_by_user_id"
        FOREIGN KEY (performed_by_user_id) REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS delivery_incident (
    delivery_incident_id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_order_id integer NOT NULL,
    reported_by_user_id text,
    incident_type varchar(60) NOT NULL,
    severity varchar(20) NOT NULL DEFAULT 'Media',
    description text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Abierto',
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    resolved_at timestamp with time zone,
    CONSTRAINT "PK_delivery_incident" PRIMARY KEY (delivery_incident_id),
    CONSTRAINT ck_delivery_incident_severity CHECK (severity IN ('Baja', 'Media', 'Alta', 'Crítica')),
    CONSTRAINT ck_delivery_incident_status CHECK (status IN ('Abierto', 'En revisión', 'Resuelto', 'Cerrado')),
    CONSTRAINT ck_delivery_incident_resolution CHECK (resolved_at IS NULL OR resolved_at >= created_at),
    CONSTRAINT "FK_delivery_incident_delivery_order_delivery_order_id"
        FOREIGN KEY (delivery_order_id) REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
    CONSTRAINT "FK_delivery_incident_AspNetUsers_reported_by_user_id"
        FOREIGN KEY (reported_by_user_id) REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    audit_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id text,
    action varchar(80) NOT NULL,
    entity_type varchar(120) NOT NULL,
    entity_id varchar(128),
    old_values jsonb,
    new_values jsonb,
    ip_address varchar(64),
    user_agent varchar(512),
    correlation_id varchar(100),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_audit_log" PRIMARY KEY (audit_log_id),
    CONSTRAINT "FK_audit_log_AspNetUsers_user_id"
        FOREIGN KEY (user_id) REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS order_status_history (
    order_status_history_id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_order_id integer NOT NULL,
    changed_by_user_id text,
    previous_status varchar(30),
    new_status varchar(30) NOT NULL,
    note varchar(500),
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    changed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_order_status_history" PRIMARY KEY (order_status_history_id),
    CONSTRAINT ck_order_status_history_previous
        CHECK (previous_status IS NULL OR previous_status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')),
    CONSTRAINT ck_order_status_history_new
        CHECK (new_status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')),
    CONSTRAINT "FK_order_status_history_delivery_order_delivery_order_id"
        FOREIGN KEY (delivery_order_id) REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
    CONSTRAINT "FK_order_status_history_AspNetUsers_changed_by_user_id"
        FOREIGN KEY (changed_by_user_id) REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS stock_reservation (
    stock_reservation_id bigint GENERATED BY DEFAULT AS IDENTITY,
    delivery_product_id integer NOT NULL,
    delivery_order_id integer NOT NULL,
    reserved_by_user_id text,
    quantity integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Activa',
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    released_at timestamp with time zone,
    CONSTRAINT "PK_stock_reservation" PRIMARY KEY (stock_reservation_id),
    CONSTRAINT ck_stock_reservation_quantity CHECK (quantity > 0),
    CONSTRAINT ck_stock_reservation_status CHECK (status IN ('Activa', 'Confirmada', 'Liberada', 'Expirada', 'Cancelada')),
    CONSTRAINT ck_stock_reservation_expiration CHECK (expires_at > created_at),
    CONSTRAINT ck_stock_reservation_release CHECK (released_at IS NULL OR released_at >= created_at),
    CONSTRAINT "FK_stock_reservation_delivery_product_delivery_product_id"
        FOREIGN KEY (delivery_product_id) REFERENCES delivery_product(delivery_product_id) ON DELETE RESTRICT,
    CONSTRAINT "FK_stock_reservation_delivery_order_delivery_order_id"
        FOREIGN KEY (delivery_order_id) REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
    CONSTRAINT "FK_stock_reservation_AspNetUsers_reserved_by_user_id"
        FOREIGN KEY (reserved_by_user_id) REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS email_queue (
    email_queue_id bigint GENERATED BY DEFAULT AS IDENTITY,
    recipient_email varchar(320) NOT NULL,
    subject varchar(255) NOT NULL,
    body_html text NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'Pendiente',
    attempt_count integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    scheduled_at timestamp with time zone NOT NULL DEFAULT now(),
    last_attempt_at timestamp with time zone,
    sent_at timestamp with time zone,
    last_error text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_email_queue" PRIMARY KEY (email_queue_id),
    CONSTRAINT ck_email_queue_attempt_count CHECK (attempt_count >= 0),
    CONSTRAINT ck_email_queue_max_attempts CHECK (max_attempts > 0 AND attempt_count <= max_attempts),
    CONSTRAINT ck_email_queue_status CHECK (status IN ('Pendiente', 'Procesando', 'Enviado', 'Fallido', 'Cancelado'))
);

CREATE TABLE IF NOT EXISTS ai_consumption_log (
    ai_consumption_log_id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id text,
    model_name varchar(120) NOT NULL,
    operation varchar(80) NOT NULL,
    prompt_tokens integer NOT NULL,
    completion_tokens integer NOT NULL,
    total_tokens integer NOT NULL,
    estimated_cost numeric(14,6) NOT NULL,
    duration_milliseconds integer NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_ai_consumption_log" PRIMARY KEY (ai_consumption_log_id),
    CONSTRAINT ck_ai_consumption_log_tokens CHECK (prompt_tokens >= 0 AND completion_tokens >= 0 AND total_tokens >= 0),
    CONSTRAINT ck_ai_consumption_log_cost CHECK (estimated_cost >= 0),
    CONSTRAINT ck_ai_consumption_log_duration CHECK (duration_milliseconds >= 0),
    CONSTRAINT "FK_ai_consumption_log_AspNetUsers_user_id"
        FOREIGN KEY (user_id) REFERENCES "AspNetUsers"("Id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS ix_inventory_movement_product_created_at
    ON inventory_movement(delivery_product_id, created_at);
CREATE INDEX IF NOT EXISTS ix_inventory_movement_order
    ON inventory_movement(delivery_order_id);
CREATE INDEX IF NOT EXISTS ix_inventory_movement_user
    ON inventory_movement(performed_by_user_id);

CREATE INDEX IF NOT EXISTS ix_delivery_incident_order_status
    ON delivery_incident(delivery_order_id, status);
CREATE INDEX IF NOT EXISTS ix_delivery_incident_reporter
    ON delivery_incident(reported_by_user_id);
CREATE INDEX IF NOT EXISTS ix_delivery_incident_created_at
    ON delivery_incident(created_at);

CREATE INDEX IF NOT EXISTS ix_audit_log_entity
    ON audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS ix_audit_log_user_created_at
    ON audit_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS ix_audit_log_created_at
    ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS ix_audit_log_correlation_id
    ON audit_log(correlation_id);

CREATE INDEX IF NOT EXISTS ix_order_status_history_order_changed_at
    ON order_status_history(delivery_order_id, changed_at);
CREATE INDEX IF NOT EXISTS ix_order_status_history_user
    ON order_status_history(changed_by_user_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_stock_reservation_active_order_product
    ON stock_reservation(delivery_order_id, delivery_product_id)
    WHERE status = 'Activa';
CREATE INDEX IF NOT EXISTS ix_stock_reservation_status_expires_at
    ON stock_reservation(status, expires_at);
CREATE INDEX IF NOT EXISTS ix_stock_reservation_product
    ON stock_reservation(delivery_product_id);
CREATE INDEX IF NOT EXISTS ix_stock_reservation_user
    ON stock_reservation(reserved_by_user_id);

CREATE INDEX IF NOT EXISTS ix_email_queue_status_scheduled_at
    ON email_queue(status, scheduled_at);
CREATE INDEX IF NOT EXISTS ix_email_queue_created_at
    ON email_queue(created_at);

CREATE INDEX IF NOT EXISTS ix_ai_consumption_log_user_created_at
    ON ai_consumption_log(user_id, created_at);
CREATE INDEX IF NOT EXISTS ix_ai_consumption_log_model_created_at
    ON ai_consumption_log(model_name, created_at);
CREATE INDEX IF NOT EXISTS ix_ai_consumption_log_created_at
    ON ai_consumption_log(created_at);
