using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace SakilaApp.Data.MigrationsIdentity;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260725153000_AgregarPagosDelivery")]
public partial class AgregarPagosDelivery : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE IF NOT EXISTS payment (
                payment_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                delivery_order_id integer NOT NULL REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
                external_id varchar(80) NOT NULL,
                provider varchar(30) NOT NULL,
                status varchar(20) NOT NULL,
                amount numeric(10,2) NOT NULL,
                created_at timestamp with time zone NOT NULL DEFAULT now(),
                confirmed_at timestamp with time zone,
                CONSTRAINT ck_payment_provider CHECK (provider IN ('PayPhone', 'PayPal')),
                CONSTRAINT ck_payment_status CHECK (status IN ('Pendiente', 'Aprobado', 'Rechazado', 'Reembolsado')),
                CONSTRAINT ck_payment_amount CHECK (amount >= 0)
            );
            CREATE INDEX IF NOT EXISTS ix_payment_order ON payment(delivery_order_id);
            CREATE INDEX IF NOT EXISTS ix_payment_created_at ON payment(created_at);
            CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_external_id ON payment(external_id);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("DROP TABLE IF EXISTS payment;");
    }
}
