using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SakilaApp.Data.MigrationsIdentity;

/// <summary>
/// Registra en el historial de EF las tablas de Orbi que ya eran administradas
/// por el script SQL. Las sentencias condicionales permiten usar la migración
/// tanto sobre bases existentes como sobre instalaciones nuevas.
/// </summary>
public partial class BaselineEsquemaOrbiExistente : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            CREATE TABLE IF NOT EXISTS delivery_store (
                delivery_store_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name varchar(100) NOT NULL,
                category varchar(60) NOT NULL,
                address varchar(180) NOT NULL,
                is_active boolean NOT NULL DEFAULT true
            );

            CREATE TABLE IF NOT EXISTS delivery_product (
                delivery_product_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                delivery_store_id integer NOT NULL REFERENCES delivery_store(delivery_store_id),
                name varchar(100) NOT NULL,
                price numeric(10,2) NOT NULL CHECK (price >= 0),
                is_available boolean NOT NULL DEFAULT true
            );

            CREATE TABLE IF NOT EXISTS delivery_order (
                delivery_order_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                delivery_store_id integer NOT NULL REFERENCES delivery_store(delivery_store_id),
                customer_email varchar(256) NOT NULL,
                delivery_person_email varchar(256),
                delivery_address varchar(180) NOT NULL,
                status varchar(30) NOT NULL DEFAULT 'Pendiente'
                    CHECK (status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')),
                total numeric(10,2) NOT NULL CHECK (total >= 0),
                created_at timestamp with time zone NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS delivery_order_item (
                delivery_order_item_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                delivery_order_id integer NOT NULL REFERENCES delivery_order(delivery_order_id) ON DELETE CASCADE,
                delivery_product_id integer NOT NULL REFERENCES delivery_product(delivery_product_id),
                product_name varchar(100) NOT NULL,
                quantity integer NOT NULL CHECK (quantity > 0),
                unit_price numeric(10,2) NOT NULL CHECK (unit_price >= 0),
                subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0)
            );

            CREATE TABLE IF NOT EXISTS ecuador_province (
                province_code varchar(2) PRIMARY KEY,
                name varchar(100) NOT NULL UNIQUE
            );

            CREATE TABLE IF NOT EXISTS ecuador_city (
                city_code varchar(4) PRIMARY KEY,
                province_code varchar(2) NOT NULL REFERENCES ecuador_province(province_code),
                name varchar(100) NOT NULL,
                UNIQUE (province_code, name)
            );

            CREATE TABLE IF NOT EXISTS user_profile (
                identity_user_id text PRIMARY KEY REFERENCES "AspNetUsers"("Id") ON DELETE CASCADE,
                first_name varchar(80) NOT NULL,
                last_name varchar(80) NOT NULL,
                cedula varchar(10) NOT NULL UNIQUE CHECK (cedula ~ '^[0-9]{10}$'),
                address_line_1 varchar(160) NOT NULL,
                address_line_2 varchar(160) NOT NULL,
                province_code varchar(2) NOT NULL REFERENCES ecuador_province(province_code),
                city_code varchar(4) NOT NULL REFERENCES ecuador_city(city_code),
                reference varchar(240),
                created_at timestamp with time zone NOT NULL DEFAULT now()
            );

            CREATE INDEX IF NOT EXISTS ix_delivery_order_customer ON delivery_order(customer_email);
            CREATE INDEX IF NOT EXISTS ix_delivery_order_driver ON delivery_order(delivery_person_email);
            CREATE INDEX IF NOT EXISTS ix_ecuador_city_province ON ecuador_city(province_code);
            CREATE INDEX IF NOT EXISTS ix_user_profile_location ON user_profile(province_code, city_code);
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Es una migración de compatibilidad: no elimina tablas preexistentes.
    }
}
