// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SakilaApp.Data;

#nullable disable

namespace SakilaApp.Data.MigrationsIdentity
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.FilmStock", b =>
                {
                    b.Property<int>("FilmStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FilmStockId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("FilmStockId");

                    b.ToTable("FilmStocks");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentTransactionId"));

                    b.Property<int>("AmountInCents")
                        .HasColumnType("integer");

                    b.Property<string>("ClientTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("text");

                    b.Property<string>("PayPalApprovalUrl")
                        .HasColumnType("text");

                    b.Property<string>("PayPalCaptureId")
                        .HasColumnType("text");

                    b.Property<string>("PayPalOrderId")
                        .HasColumnType("text");

                    b.Property<string>("PayphonePaymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("PayphoneTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.PurchaseOrder", b =>
                {
                    b.Property<int>("PurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PurchaseOrderId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.PurchaseOrderDetail", b =>
                {
                    b.Property<int>("PurchaseOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PurchaseOrderDetailId"));

                    b.Property<int>("FilmStockId")
                        .HasColumnType("integer");

                    b.Property<string>("FilmTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchaseOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("PurchaseOrderDetailId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderDetails");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShoppingCartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilmStockId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("FilmStockId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryOrder", b =>
                {
                    b.Property<int>("DeliveryOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryOrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("customer_email");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("delivery_address");

                    b.Property<string>("DeliveryPersonEmail")
                        .HasColumnType("text")
                        .HasColumnName("delivery_person_email");

                    b.Property<int>("DeliveryStoreId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_store_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("DeliveryOrderId");

                    b.HasIndex("DeliveryStoreId");

                    b.ToTable("delivery_order", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryOrderItem", b =>
                {
                    b.Property<int>("DeliveryOrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryOrderItemId"));

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<int>("DeliveryProductId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_product_id");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("product_name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("DeliveryOrderItemId");

                    b.HasIndex("DeliveryOrderId");

                    b.ToTable("delivery_order_item", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryProduct", b =>
                {
                    b.Property<int>("DeliveryProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delivery_product_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryProductId"));

                    b.Property<int>("DeliveryStoreId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_store_id");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_available");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("DeliveryProductId");

                    b.HasIndex("DeliveryStoreId");

                    b.ToTable("delivery_product", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryPayment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("external_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("PaymentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_payment_created_at");

                    b.HasIndex("DeliveryOrderId")
                        .HasDatabaseName("ix_payment_order");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_external_id");

                    b.ToTable("payment", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_amount", "amount >= 0");
                            t.HasCheckConstraint("ck_payment_provider", "provider IN ('PayPhone', 'PayPal')");
                            t.HasCheckConstraint("ck_payment_status", "status IN ('Pendiente', 'Aprobado', 'Rechazado', 'Reembolsado')");
                        });
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryStore", b =>
                {
                    b.Property<int>("DeliveryStoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("delivery_store_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DeliveryStoreId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("DeliveryStoreId");

                    b.ToTable("delivery_store", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Identity.EcuadorCity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("city_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("province_code");

                    b.HasKey("Code");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("ecuador_city", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Identity.EcuadorProvince", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("province_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("ecuador_province", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Identity.UserProfile", b =>
                {
                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text")
                        .HasColumnName("identity_user_id");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("address_line_1");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("address_line_2");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("cedula");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("city_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("last_name");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("province_code");

                    b.Property<string>("Reference")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("reference");

                    b.HasKey("IdentityUserId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("CityCode");

                    b.HasIndex("ProvinceCode");

                    b.ToTable("user_profile", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.AiConsumptionLog", b =>
                {
                    b.Property<long>("AiConsumptionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ai_consumption_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AiConsumptionLogId"));

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_milliseconds");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric(14,6)")
                        .HasColumnName("estimated_cost");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model_name");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("operation");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("AiConsumptionLogId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_ai_consumption_log_created_at");

                    b.HasIndex("ModelName", "CreatedAt")
                        .HasDatabaseName("ix_ai_consumption_log_model_created_at");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_ai_consumption_log_user_created_at");

                    b.ToTable("ai_consumption_log", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_consumption_log_cost", "estimated_cost >= 0");

                            t.HasCheckConstraint("ck_ai_consumption_log_duration", "duration_milliseconds >= 0");

                            t.HasCheckConstraint("ck_ai_consumption_log_tokens", "prompt_tokens >= 0 AND completion_tokens >= 0 AND total_tokens >= 0");
                        });
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntityId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_values");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("AuditLogId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_log_correlation_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_log_created_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_log_entity");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_audit_log_user_created_at");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.DeliveryIncident", b =>
                {
                    b.Property<long>("DeliveryIncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_incident_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DeliveryIncidentId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("incident_type");

                    b.Property<string>("ReportedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("reported_by_user_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Media")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Abierto")
                        .HasColumnName("status");

                    b.HasKey("DeliveryIncidentId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_delivery_incident_created_at");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_delivery_incident_reporter");

                    b.HasIndex("DeliveryOrderId", "Status")
                        .HasDatabaseName("ix_delivery_incident_order_status");

                    b.ToTable("delivery_incident", null, t =>
                        {
                            t.HasCheckConstraint("ck_delivery_incident_resolution", "resolved_at IS NULL OR resolved_at >= created_at");

                            t.HasCheckConstraint("ck_delivery_incident_severity", "severity IN ('Baja', 'Media', 'Alta', 'Crítica')");

                            t.HasCheckConstraint("ck_delivery_incident_status", "status IN ('Abierto', 'En revisión', 'Resuelto', 'Cerrado')");
                        });
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.EmailQueueItem", b =>
                {
                    b.Property<long>("EmailQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("email_queue_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EmailQueueId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_html");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.HasKey("EmailQueueId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_email_queue_created_at");

                    b.HasIndex("Status", "ScheduledAt")
                        .HasDatabaseName("ix_email_queue_status_scheduled_at");

                    b.ToTable("email_queue", null, t =>
                        {
                            t.HasCheckConstraint("ck_email_queue_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_email_queue_max_attempts", "max_attempts > 0 AND attempt_count <= max_attempts");

                            t.HasCheckConstraint("ck_email_queue_status", "status IN ('Pendiente', 'Procesando', 'Enviado', 'Fallido', 'Cancelado')");
                        });
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.InventoryMovement", b =>
                {
                    b.Property<long>("InventoryMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("inventory_movement_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InventoryMovementId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<int>("DeliveryProductId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_product_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("movement_type");

                    b.Property<string>("PerformedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("performed_by_user_id");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_cost");

                    b.HasKey("InventoryMovementId");

                    b.HasIndex("DeliveryOrderId")
                        .HasDatabaseName("ix_inventory_movement_order");

                    b.HasIndex("PerformedByUserId")
                        .HasDatabaseName("ix_inventory_movement_user");

                    b.HasIndex("DeliveryProductId", "CreatedAt")
                        .HasDatabaseName("ix_inventory_movement_product_created_at");

                    b.ToTable("inventory_movement", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movement_quantity_delta", "quantity_delta <> 0");

                            t.HasCheckConstraint("ck_inventory_movement_type", "movement_type IN ('Entrada', 'Salida', 'Ajuste', 'Reserva', 'Liberación')");

                            t.HasCheckConstraint("ck_inventory_movement_unit_cost", "unit_cost IS NULL OR unit_cost >= 0");
                        });
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.OrderStatusHistory", b =>
                {
                    b.Property<long>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("order_status_history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OrderStatusHistoryId"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("new_status");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("previous_status");

                    b.HasKey("OrderStatusHistoryId");

                    b.HasIndex("ChangedByUserId")
                        .HasDatabaseName("ix_order_status_history_user");

                    b.HasIndex("DeliveryOrderId", "ChangedAt")
                        .HasDatabaseName("ix_order_status_history_order_changed_at");

                    b.ToTable("order_status_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_order_status_history_new", "new_status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')");

                            t.HasCheckConstraint("ck_order_status_history_previous", "previous_status IS NULL OR previous_status IN ('Pendiente', 'En preparación', 'En camino', 'Entregado', 'Cancelado')");
                        });
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.StockReservation", b =>
                {
                    b.Property<long>("StockReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("stock_reservation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StockReservationId"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DeliveryOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_order_id");

                    b.Property<int>("DeliveryProductId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_product_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<string>("ReservedByUserId")
                        .HasColumnType("text")
                        .HasColumnName("reserved_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Activa")
                        .HasColumnName("status");

                    b.HasKey("StockReservationId");

                    b.HasIndex("DeliveryProductId")
                        .HasDatabaseName("ix_stock_reservation_product");

                    b.HasIndex("ReservedByUserId")
                        .HasDatabaseName("ix_stock_reservation_user");

                    b.HasIndex("DeliveryOrderId", "DeliveryProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_reservation_active_order_product")
                        .HasFilter("status = 'Activa'");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_stock_reservation_status_expires_at");

                    b.ToTable("stock_reservation", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_reservation_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_stock_reservation_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_stock_reservation_release", "released_at IS NULL OR released_at >= created_at");

                            t.HasCheckConstraint("ck_stock_reservation_status", "status IN ('Activa', 'Confirmada', 'Liberada', 'Expirada', 'Cancelada')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.PaymentTransaction", b =>
                {
                    b.HasOne("SakilaApp.Models.Commerce.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.PurchaseOrderDetail", b =>
                {
                    b.HasOne("SakilaApp.Models.Commerce.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.ShoppingCartItem", b =>
                {
                    b.HasOne("SakilaApp.Models.Commerce.FilmStock", "FilmStock")
                        .WithMany()
                        .HasForeignKey("FilmStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilmStock");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryOrder", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryStore", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryOrderItem", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryOrder", "Order")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryProduct", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryStore", "Store")
                        .WithMany("Products")
                        .HasForeignKey("DeliveryStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryPayment", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryOrder", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SakilaApp.Models.Identity.EcuadorCity", b =>
                {
                    b.HasOne("SakilaApp.Models.Identity.EcuadorProvince", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SakilaApp.Models.Identity.UserProfile", b =>
                {
                    b.HasOne("SakilaApp.Models.Identity.EcuadorCity", "City")
                        .WithMany()
                        .HasForeignKey("CityCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("SakilaApp.Models.Identity.UserProfile", "IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakilaApp.Models.Identity.EcuadorProvince", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.AiConsumptionLog", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.AuditLog", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.DeliveryIncident", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryOrder", "Order")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.InventoryMovement", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryOrder", "Order")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SakilaApp.Models.Delivery.DeliveryProduct", "Product")
                        .WithMany()
                        .HasForeignKey("DeliveryProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("PerformedByUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.OrderStatusHistory", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SakilaApp.Models.Delivery.DeliveryOrder", "Order")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SakilaApp.Models.Operations.StockReservation", b =>
                {
                    b.HasOne("SakilaApp.Models.Delivery.DeliveryOrder", "Order")
                        .WithMany()
                        .HasForeignKey("DeliveryOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SakilaApp.Models.Delivery.DeliveryProduct", "Product")
                        .WithMany()
                        .HasForeignKey("DeliveryProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "ReservedByUser")
                        .WithMany()
                        .HasForeignKey("ReservedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ReservedByUser");
                });

            modelBuilder.Entity("SakilaApp.Models.Commerce.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryOrder", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SakilaApp.Models.Delivery.DeliveryStore", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SakilaApp.Models.Identity.EcuadorProvince", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
